# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# To run use: `fastlane ios screenshots`.

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_ios_screenshots(workspace: "Psiphon.xcworkspace",
                            scheme: "PsiphonUITests",
                            stop_after_first_error: true,
                            derived_data_path: "~/Library/Developer/Xcode/DerivedData/",
                            # Do not rebuild for every device/language combination.
                            test_without_building: true,
                            concurrent_simulators: true,
                            dark_mode: true)
    upload_to_app_store(skip_binary_upload: true,
                        skip_metadata: true, 
                        overwrite_screenshots: true,
                        screenshots_path: 'StoreAssets/screenshots')
  end
end
