# Uncomment the lines below you want to change by removing the # in the beginning
#ios_version '11.0.1'

# A list of devices you want to take the screenshots from
devices([
#  "iPhone 5s",
#  "iPhone 6",
#  "iPhone 6 Plus",
   "iPhone 6s",
#  "iPhone 6s Plus",
#  "iPhone 7",
#  "iPhone 7 Plus",
   "iPhone 8",
#  "iPhone 8 Plus",
#  "iPad Air",
#  "iPad Air 2",
#  "iPad Air (3rd generation)",
#  "iPad (5th generation)",
#  "iPad (7th generation)",
#  "iPad Pro (9.7 inch)",
#  "iPad Pro (10.5-inch)",
#  "iPad Pro (11-inch)",
  "iPad Pro (12.9-inch)",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPhone X",
  "iPhone Xs Max",
  "iPhone 11"
#  "iPhone 11 Pro",
#  "iPhone 11 Pro Max"
 ])

languages([
  #"am",
  #"ar",
  #"az",
  #"be",
  #"bo",
  "de-DE",
  "el",
  "en-US",
  "es-ES",
  #"fa",
  "fi",
  "fr-FR",
  #"hr",
  "id",
  #"kk",
  #"km",
  "ko",
  #"ky",
  #"my",
  "no",
  "nl-NL",
  "pt-BR",
  "pt-PT",
  "ru",
  "th",
  #"tk",
  "tr",
  #"uk",
  #"uz",
  "vi",
  "zh-Hans",
  "zh-Hant"
  #["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme "Psiphon"

# Where should the resulting screenshots be stored?
output_directory "./StoreAssets/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/
launch_arguments(["-FASTLANE_SNAPSHOT YES"])

# For more information about all available options run
# fastlane snapshot --help

# Disable concurrent simulators.
# In the past running with concurrent simulators has caused issues.
concurrent_simulators false
