# Uncomment the lines below you want to change by removing the # in the beginning
#ios_version '11.0.1'

# A list of devices you want to take the screenshots from
devices([
  "iPhone 5s",
  "iPhone 6s Plus",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPhone Xs Max",
 ])

languages([
  #"am",
  #"ar",
  #"az",
  #"be",
  #"bo",
  "de-DE",
  "el",
  "en-US",
  "es-ES",
  #"fa",
  "fi",
  "fr-FR",
  #"hr",
  "id",
  #"kk",
  #"km",
  "ko",
  #"ky",
  #"my",
  "no",
  "nl-NL",
  "pt-BR",
  "pt-PT",
  "ru",
  "th",
  #"tk",
  "tr",
  #"uk",
  #"uz",
  "vi",
  "zh-Hans",
  "zh-Hant"
  #["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme "PsiphonUITests"

# Where should the resulting screenshots be stored?
output_directory "./StoreAssets/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/
launch_arguments(["-FASTLANE_SNAPSHOT YES"])

# In the past disabling concurrent simulators has helped fix issues
# encountered when generating screenshots.
# concurrent_simulators false

# For more information about all available options run
# fastlane snapshot --help

