/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Simplified-PKCS7"
 * 	found in "pkcs7-signed-data-simplified.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ReceiptAttributes_H_
#define	_ReceiptAttributes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReceiptAttribute;

/* ReceiptAttributes */
typedef struct ReceiptAttributes {
	A_SET_OF(struct ReceiptAttribute) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceiptAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptAttributes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReceiptAttribute.h"

#endif	/* _ReceiptAttributes_H_ */
#include <asn_internal.h>
