/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Simplified-PKCS7"
 * 	found in "pkcs7-signed-data-simplified.asn1"
 * 	`asn1c -fnative-types`
 */

#include "SignedData.h"

static asn_TYPE_member_t asn_MBR_contentInfo_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct contentInfo, contentType),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct contentInfo, contentData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentData"
		},
};
static const ber_tlv_tag_t asn_DEF_contentInfo_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_contentInfo_tag2el_6[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* contentType */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* contentData */
};
static asn_SEQUENCE_specifics_t asn_SPC_contentInfo_specs_6 = {
	sizeof(struct contentInfo),
	offsetof(struct contentInfo, _asn_ctx),
	asn_MAP_contentInfo_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_contentInfo_6 = {
	"contentInfo",
	"contentInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_contentInfo_tags_6,
	sizeof(asn_DEF_contentInfo_tags_6)
		/sizeof(asn_DEF_contentInfo_tags_6[0]), /* 1 */
	asn_DEF_contentInfo_tags_6,	/* Same as above */
	sizeof(asn_DEF_contentInfo_tags_6)
		/sizeof(asn_DEF_contentInfo_tags_6[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_contentInfo_6,
	2,	/* Elements count */
	&asn_SPC_contentInfo_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_content_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct content, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct content, digestAlgorithms),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"digestAlgorithms"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct content, contentInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_contentInfo_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_content_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_content_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* contentInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_content_specs_3 = {
	sizeof(struct content),
	offsetof(struct content, _asn_ctx),
	asn_MAP_content_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_content_3 = {
	"content",
	"content",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_content_tags_3,
	sizeof(asn_DEF_content_tags_3)
		/sizeof(asn_DEF_content_tags_3[0]), /* 2 */
	asn_DEF_content_tags_3,	/* Same as above */
	sizeof(asn_DEF_content_tags_3)
		/sizeof(asn_DEF_content_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_content_3,
	3,	/* Elements count */
	&asn_SPC_content_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SignedData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignedData, contentType),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedData, content),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_content_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"content"
		},
};
static const ber_tlv_tag_t asn_DEF_SignedData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SignedData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* contentType */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* content */
};
static asn_SEQUENCE_specifics_t asn_SPC_SignedData_specs_1 = {
	sizeof(struct SignedData),
	offsetof(struct SignedData, _asn_ctx),
	asn_MAP_SignedData_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SignedData = {
	"SignedData",
	"SignedData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SignedData_tags_1,
	sizeof(asn_DEF_SignedData_tags_1)
		/sizeof(asn_DEF_SignedData_tags_1[0]), /* 1 */
	asn_DEF_SignedData_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignedData_tags_1)
		/sizeof(asn_DEF_SignedData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SignedData_1,
	2,	/* Elements count */
	&asn_SPC_SignedData_specs_1	/* Additional specs */
};

