/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Simplified-PKCS7"
 * 	found in "pkcs7-signed-data-simplified.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_SignedData_H_
#define	_SignedData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"
#include "NativeInteger.h"
#include "ANY.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignedData */
typedef struct SignedData {
	OBJECT_IDENTIFIER_t	 contentType;
	struct content {
		long	 version;
		ANY_t	 digestAlgorithms;
		struct contentInfo {
			OBJECT_IDENTIFIER_t	 contentType;
			OCTET_STRING_t	 contentData;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} contentInfo;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} content;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedData;

#ifdef __cplusplus
}
#endif

#endif	/* _SignedData_H_ */
#include "asn_internal.h"
